python ../../OpenNMT-py/train.py -data /tigress/fdamani/mol-edit-data/data/qed/onmt-new \
				-global_attention general \
				-src_word_vec_size 500 \
				-tgt_word_vec_size 500 \
				-encoder_type transformer \
				-decoder_type transformer \
				-heads 8 \
				-self_attn_type scaled-dot \
				-param_init_glorot True \
				-rnn_type LSTM \
				-save_model /tigress/fdamani/mol-edit-output/onmt-qed/model-1layer-500wordembed-500embed-transformer-adamoptim \
				-train_steps 100000 \
				-valid_steps 10000 \
				-batch_size 64 \
				-save_checkpoint_steps 5000 \
				-report_every 200 \
				-world_size 1 \
				-gpu_ranks 0 \
				-optim adam \
				-learning_rate 0.001